In [1]:
import pandas as pd
import numpy as np

In [2]:
f = './data/Arneson_Horvath_2022/mammal_to_450karray.xlsx'
df = pd.read_excel(f, skiprows=2)
df

,Row,Human Array ID,List,OnMammalArray,mapsToRat,mapsToMouse
0,1,cg00075967,Horvath2013.353CpGs,yes,0,0
1,2,cg00374717,Horvath2013.353CpGs,yes,0,0
2,3,cg00864867,Horvath2013.353CpGs,yes,0,0
3,4,cg00945507,Horvath2013.353CpGs,yes,0,0
4,5,cg01027739,Horvath2013.353CpGs,yes,0,0
...,...,...,...,...,...,...
2018,2100,cg19015086,SkinAndFibroblastClock233Horvath,yes,0,0
2019,2102,cg00343092,SkinAndFibroblastClock233Horvath,yes,0,0
2020,2103,cg27131176,SkinAndFibroblastClock233Horvath,yes,0,0
2021,2104,cg22982767,SkinAndFibroblastClock233Horvath,yes,0,0
2022,2105,cg01892695,SkinAndFibroblastClock233Horvath,yes,0,0

In [3]:
(df['OnMammalArray'] == 'yes').sum()

1982

In [4]:
f = './data/Arneson_Horvath_2022/mammal_to_mm10.csv'
df2 = pd.read_csv(f) #(f, skiprows=2)
df2 = df2[~df2['seqnames'].isnull()]
df2

,Unnamed: 0,CGid,SYMBOL,GeneRegionID,seqnames,probeStart,probeEnd,CGstart,CGend,width,...,CpGislandwidth,CpGislandstrand,CpGislandlen,CpGislandcount,CpGislandgc,CpGislandoe,CpGislandden,CpGislandpvalue,CpGisland,CG
1,2,cg00001209,Gm2736,Gm2736_Intergenic_upstream,13,107337144.0,107337193.0,107337192.0,107337193.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
2,3,cg00001364,Prox1,Prox1_Exon,1,190161748.0,190161797.0,190161748.0,190161749.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
3,4,cg00001582,Zmiz1,Zmiz1_fiveUTR,14,25459181.0,25459230.0,25459229.0,25459230.0,50.0,...,410.0,*,410.0,55.0,0.704878,1.080084,0.134146,7.653479e-50,CpGisland,True
4,5,cg00002920,Gm9341,Gm9341_Intergenic_downstream,7,136057334.0,136057383.0,136057382.0,136057383.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
5,6,cg00003994,Meox2,Meox2_Exon,12,37108995.0,37109044.0,37108995.0,37108996.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37482,37483,cg27725202,Asf1a,Asf1a_fiveUTR,10,53596814.0,53596863.0,53596814.0,53596815.0,50.0,...,420.0,*,420.0,52.0,0.738095,0.922921,0.123810,4.683232e-45,CpGisland,True
37483,37484,cg27725275,Asf1a,Asf1a_fiveUTR,10,53596800.0,53596849.0,53596848.0,53596849.0,50.0,...,420.0,*,420.0,52.0,0.738095,0.922921,0.123810,4.683232e-45,CpGisland,True
37485,37486,cg27728043,Gm10051,Gm10051_Intergenic_downstream,5,133479301.0,133479350.0,133479301.0,133479302.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
37486,37487,cg27735940,Gm10051,Gm10051_Intergenic_downstream,5,133482428.0,133482477.0,133482476.0,133482477.0,50.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True
37487,37488,cg27742797,Hs6st2,Hs6st2_Exon,X,51681247.0,51681296.0,51681295.0,51681296.0,50.0,...,1186.0,*,1186.0,115.0,0.697302,0.813414,0.096965,2.224152e-85,CpGisland,True

In [5]:
genepanels = [
    'Trpm3',
    'Tyr',
    
    'Hdgfrp3',
    'Mycn',
    
    'Loxl4',
    'Hotair',
]
np.intersect1d(genepanels, df2['SYMBOL'].values)

array(['Mycn', 'Trpm3'], dtype=object)